package id.dreamfighter.android.compose.tojson

val payloadMajidTv = """
{
   "listItems":[
      {
         "type":"IMAGE",
         "message":"Hello Here",
         "props":{"contentScale":"FillWidth","fillMaxWidth":true},
         "backgroundColor": "GREEN"
      },
      {
        "type":"COLUMN",
         "listItems":[
            {
                "type":"BOX",
                "props":{"fillMaxWidth":true},
                "listItems":[
                    {
                        "type":"ROW",
                        "props":{
                            "height":90,
                            "background":"#55000000",
                            "align":"CENTER"
                        },
                        "listItems":[
                            {
                                 "type":"TEXT",
                                 "message":"Sabtu, 11 Mar 2023\n19 Sha'ban 1444",
                                 "textAlign":"START",
                                 "alignment":"CENTER",
                                 "color":"#FFFFFFFF",
                                 "textFont":20,
                                 "props":{
                                    "padding":{"start":16}
                                 }
                            },{
                                 "type":"TEXT",
                                 "message":"Masjid AT-Taqwa Pesona Ciganitri",
                                 "textAlign":"CENTER",
                                 "alignment":"CENTER",
                                 "color":"#FFFFFFFF",
                                 "textFont":30,
                                 "props":{
                                    "padding":{"start":16,"end":16}
                                 },
                                 "weight":1.0
                            },{
                                 "type":"TEXT",
                                 "message":"11:50:00",
                                 "textAlign":"CENTER",
                                 "alignment":"CENTER",
                                 "color":"#FFFFFFFF",
                                 "textFont":50,
                                 "props":{
                                    "padding":{"start":16,"end":16}
                                 }
                            }
                        ]
                    }
                ]
            },{
                "type":"BOX",
                "props":{"fillMaxWidth":true}
            },{
                "type":"TEXT",
                "message":"Sabtu, 11 Mar 2023, 19 Sha'ban 1444, Sabtu, 11 Mar 2023, 19 Sha'ban 1444 Sabtu, 11 Mar 2023, 19 Sha'ban 1444 Sabtu, 11 Mar 2023, 19 Sha'ban 1444 Sabtu, 11 Mar 2023, 19 Sha'ban 1444 Sabtu, 11 Mar 2023, 19 Sha'ban 1444",
                "textAlign":"CENTER",
                "maxLines":1,
                "alignment":"CENTER",
                "color":"#FFFFFFFF",
                "textFont":50
            }
         ]
      }
   ]
}
""".trimIndent()

val payloadOne = """
{
   "listItems":[
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"IMAGE",
               "message":"Hello Here",
               "backgroundColor": "GREEN"
               
            },
            {
               "type":"IMAGE",
               "message":"Thank You!!",
               "backgroundColor": "BLUE"
            },
            {
                "type":"SOMETHING ELSE"
            }
         ]
      }
   ]
}
""".trimIndent()

val payloadMany = """
{
   "listItems":[
      {
         "type":"TEXT",
         "message":"Dyno Text",
         "textAlign":"CENTER",
         "textFont":"DEFAULT",
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"TEXT",
         "message":"Dyno Text",
         "textAlign":"CENTER",
         "textFont":"DEFAULT",
         "alignment":"START",
         "weight":0.0
      },
      {
         "type":"TEXT",
         "message":"Dyno Text",
         "textAlign":"CENTER",
         "textFont":"DEFAULT",
         "alignment":"END",
         "weight":0.0
      },
      {
         "type":"BUTTON",
         "message":"Dyno Button",
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"BUTTON",
         "message":"Dyno Button",
         "alignment":"START",
         "weight":0.0
      },
      {
         "type":"BUTTON",
         "message":"Dyno Button",
         "alignment":"END",
         "weight":0.0
      },
      {
         "type":"IMAGE",
         "imageAlign":"CENTER",
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"IMAGE",
         "imageAlign":"CENTER",
         "alignment":"START",
         "weight":0.0
      },
      {
         "type":"IMAGE",
         "imageAlign":"CENTER",
         "alignment":"END",
         "weight":0.0
      },
      {
         "type":"COLUMN",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Column Dyno Text",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":0.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":0.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"COLUMN",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Column Dyno Text Start",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"START",
               "weight":0.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":0.0
            },
            {
               "type":"TEXT",
               "message":"Column Dyno Text End",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"END",
               "weight":0.0
            }
         ],
         "alignment":"FILL",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Hello Dyno Text",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Hello Dyno Text",
               "textAlign":"START",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"END",
               "alignment":"CENTER",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Hello Dyno Text",
               "textAlign":"END",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"START",
               "alignment":"CENTER",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Row Start",
               "textAlign":"START",
               "textFont":"SMALL",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"TEXT",
               "message":"Row End",
               "textAlign":"END",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"COLUMN",
         "listItems":[
            {
               "type":"ROW",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Row Dyno Text",
                     "textAlign":"CENTER",
                     "textFont":"DEFAULT",
                     "alignment":"CENTER",
                     "weight":0.0
                  },
                  {
                     "type":"IMAGE",
                     "imageAlign":"CENTER",
                     "alignment":"CENTER",
                     "weight":0.0
                  }
               ],
               "alignment":"CENTER",
               "weight":0.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":0.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"COLUMN",
         "listItems":[
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"CENTER",
               "weight":0.0
            },
            {
               "type":"ROW",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Row Dyno Text",
                     "textAlign":"CENTER",
                     "textFont":"DEFAULT",
                     "alignment":"CENTER",
                     "weight":0.0
                  },
                  {
                     "type":"IMAGE",
                     "imageAlign":"CENTER",
                     "alignment":"END",
                     "weight":0.0
                  }
               ],
               "alignment":"CENTER",
               "weight":0.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"TEXT",
               "message":"Row Dyno Text",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":1.0
            },
            {
               "type":"COLUMN",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Column Dyno Text",
                     "textAlign":"CENTER",
                     "textFont":"DEFAULT",
                     "alignment":"CENTER",
                     "weight":0.0
                  },
                  {
                     "type":"IMAGE",
                     "imageAlign":"CENTER",
                     "alignment":"END",
                     "weight":0.0
                  }
               ],
               "alignment":"CENTER",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"COLUMN",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Column Dyno Text",
                     "textAlign":"CENTER",
                     "textFont":"DEFAULT",
                     "alignment":"CENTER",
                     "weight":0.0
                  },
                  {
                     "type":"IMAGE",
                     "imageAlign":"CENTER",
                     "alignment":"CENTER",
                     "weight":0.0
                  }
               ],
               "alignment":"CENTER",
               "weight":0.0
            },
            {
               "type":"TEXT",
               "message":"Row Dyno Text",
               "textAlign":"CENTER",
               "textFont":"DEFAULT",
               "alignment":"CENTER",
               "weight":0.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
     {
         "type":"ROW",
         "listItems":[
            {
               "type":"COLUMN",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Mr Charming",
                     "textAlign":"CENTER",
                     "textFont":"HUGE",
                     "alignment":"START",
                     "backgroundColor":"RED",
                     "weight":0.0
                  },
                  {
                     "type":"TEXT",
                     "message":"10001 Some Nice Road\nGreat Suburb 1234\nHeaven",
                     "textAlign":"START",
                     "textFont":"DEFAULT",
                     "alignment":"START",
                     "weight":0.0
                  }
               ],
               "alignment":"FILL",
               "weight":1.0
            },
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"END",
               "backgroundColor":"GREEN",
               "weight":0.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"END",
               "weight":0.0
            },
            {
               "type":"COLUMN",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Mr Smart",
                     "textAlign":"CENTER",
                     "textFont":"HUGE",
                     "alignment":"START",
                     "weight":0.0
                  },
                  {
                     "type":"TEXT",
                     "message":"10001 Some Nice Road\nGreat Suburb 1234\nHeaven",
                     "textAlign":"START",
                     "textFont":"DEFAULT",
                     "alignment":"START",
                     "weight":0.0
                  }
               ],
               "alignment":"FILL",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      },
      {
         "type":"ROW",
         "listItems":[
            {
               "type":"IMAGE",
               "imageAlign":"CENTER",
               "alignment":"END",
               "weight":0.0
            },
            {
               "type":"COLUMN",
               "listItems":[
                  {
                     "type":"TEXT",
                     "message":"Mr Handsome",
                     "textAlign":"CENTER",
                     "textFont":"HUGE",
                     "alignment":"CENTER",
                     "backgroundColor":"BLUE",
                     "weight":0.0
                  },
                  {
                     "type":"TEXT",
                     "message":"10001 Some Nice Road\nGreat Suburb 1234\nHeaven",
                     "textAlign":"CENTER",
                     "textFont":"DEFAULT",
                     "alignment":"CENTER",
                     "weight":0.0
                  }
               ],
               "alignment":"FILL",
               "weight":1.0
            }
         ],
         "alignment":"CENTER",
         "weight":0.0
      }      
   ]
}    
""".trimIndent()